### ISSUE TITLE
Possible BUG with concurrent stream limit

### ISSUE THREAD

**Issue by Shadowalker125** [connorgallopo/Tracearr#67]
I have the concurrent stream limit set to default of 3. One of my users watched a show back-to-back and each new episode triggered an event over the concurrent limit. This gave the user 17 violations in one sitting. 

<img width="762" height="582" alt="Image" src="https://github.com/user-attachments/assets/7faa6b74-32aa-42ff-9d45-9dd99bc391dd" />

It might be because the stop and start times are the same, but im not sure why considering I have the limit at 3 and not 2. 

<img width="320" height="376" alt="Image" src="https://github.com/user-attachments/assets/b186232d-0f92-4e67-9739-66d0c56c6982" />

**Comment by Brendon-MB** [comment]
I am seeing a very similar problem, only for me it was triggering Impossible Travel (I do not have concurrent streams rule on) so I disabled that rule and then it started triggering Simultaneous Locations over and over, behaviour is just as OP has posted.

**Comment by connorgallopo** [comment]
@Brendon-MB @Shadowalker125 

What version of Tracearr are you running?

If you havent recently, please pull! I addressed this in a couple different areas and hardened it.

The issues i addressed were that each "stream" in breaking the rule would trigger an alert. with no "timeout". Now that cant happen

**Comment by Brendon-MB** [comment]
@connorgallopo I am running Tracearr supervised-v1.3.8 / Emby Version 4.9.1.90 I have had to turn off all rules because of the above, as i disabled one it started throwing alerts for another rule so i disabled them all.

**Comment by connorgallopo** [comment]
Hmm you can see if going to the `supervised-next` release fixes it - but ill ahve to replicate to be confident. Which i will do

**Comment by Shadowalker125** [comment]
Im currently using supervised latest, up to date, still getting new violations.

**Comment by connorgallopo** [comment]
@Shadowalker125 supervised-next is the beta, and ahead of the latest `supervised` tag

**Comment by connorgallopo** [comment]
But as it sits - I need to write a lot of tests here to TDD this. And write cases for things that should never trigger. A ton of work has just been put in to clean up things like data normalization across all the platforms and there is still a bit of a ways to go.

**Comment by connorgallopo** [comment]
This should be improved in latest beta that is about to release @Shadowalker125

**Comment by connorgallopo** [comment]
Should be good! Ping me if you see it still after being on 1.3.9-beta.6 or the next stable!
