### ISSUE TITLE
Installing "supervised" from the official Unraid repositry

### ISSUE THREAD

**Issue by WildWayz** [connorgallopo/Tracearr#7]
Hey Connor

I just saw this on Unraid's repositry so I thought I would try out the Tracearr-Supervised build.
I am getting an error when running the install:

` --restart=unless-stopped 'ghcr.io/connorgallopo/tracearr:supervised'
Unable to find image 'ghcr.io/connorgallopo/tracearr:supervised' locally
docker: Error response from daemon: manifest unknown.
See 'docker run --help'.`

I assume the tag "supervised" hasn't been created.

Is it still being worked on?

It is so it installs Redis etc as an all in one installer rather than manually setting the details.

Thanks

**Comment by Laguna85** [comment]
Hi, switching to nightly due the same error. I was able to install it but no docker container has been created. As you can see no container ip assigned. I can't even see any logs. 

<img width="1404" height="65" alt="Image" src="https://github.com/user-attachments/assets/25c11021-a742-4683-85fb-a16aea5ab42e" />

**Comment by WildWayz** [comment]
I think Nightly installs the normal release of Tracearr - so it'll install but there will be no variables for the redis and database etc. You'll notice it doesn't start and logs close straight away.

**Comment by JamsRepos** [comment]
Yeah, doesn't seem to start and just halts at:
```
[Tracearr] Loaded JWT_SECRET from persistent storage
[Tracearr] Loaded COOKIE_SECRET from persistent storage
[Tracearr] Loaded ENCRYPTION_KEY from persistent storage
[Tracearr] Initializing PostgreSQL database...
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "C".
The default database encoding has accordingly been set to "SQL_ASCII".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /data/postgres ... 
```
Then boot loops.

**Comment by connorgallopo** [comment]
Hi @Laguna85 @JamsRepos @WildWayz! Thanks for submitting this!

I am looking into this right now. I just pushed an fix for one other issue I found; And will have this resolved shortly!

**Comment by connorgallopo** [comment]
Ahh - It's because I need to release the first production release. I will do that here in a moment! 

I have been working on this heads down in isolation as nobody really knew about it.. But now that it's on Unraid I will move to proper release / PR flows!

**Comment by connorgallopo** [comment]
I also have a fix in the works for that postgres issue. I am just recreating it locally with some docker volumes and trying to put a safe fix in place

**Comment by connorgallopo** [comment]
Ok - The postgres issue also is related to my lack of UID/GUID handling in template. It was my first one, so apologies for my oversight!

**Comment by JamsRepos** [comment]
> Ok - The postgres issue also is related to my lack of UID/GUID handling in template. It was my first one, so apologies for my oversight! 

I added those myself and it still failed but I could've not cleared the directory properly to be honest, I'll pull the latest template when it's live though and try again.

**Comment by connorgallopo** [comment]
> > Ok - The postgres issue also is related to my lack of UID/GUID handling in template. It was my first one, so apologies for my oversight!
> 
> I added those myself and it still failed but I could've not cleared the directory properly to be honest, I'll pull the latest template when it's live though and try again.

There was another part I added - which was a failed initialization check, as well as some directory creation/chown that I saw were in redis/psql templates/dockerfiles.. So between those I hope to see it fixed. I know in the discord one user does have supervised installed. Not sure how they got around this - but I'm hopeful this fix will address it.

It will be included in the release I tag - as it's not just a template change.

Thank you for your patience!

**Comment by connorgallopo** [comment]
I pushed what i believe addresses everything! @JamsRepos @WildWayz @Laguna85. As of this moment in time nightly tag is not up-to-date but everything else is!

**Comment by JamsRepos** [comment]
> I pushed what i believe addresses everything! [@JamsRepos](https://github.com/JamsRepos) [@WildWayz](https://github.com/WildWayz) [@Laguna85](https://github.com/Laguna85). As of this moment in time nightly tag is not up-to-date but everything else is!

I can confirm it's now working on the main image, cheers!

**Comment by connorgallopo** [comment]
> > I pushed what i believe addresses everything! [@JamsRepos](https://github.com/JamsRepos) [@WildWayz](https://github.com/WildWayz) [@Laguna85](https://github.com/Laguna85). As of this moment in time nightly tag is not up-to-date but everything else is!
> 
> I can confirm it's now working on the main image, cheers!

Awesome! Thank you for the confirmation!
